#!/usr/bin/env python3
"""
HTML to Arduino PROGMEM Converter
Converts HTML files to compressed PROGMEM strings for Arduino projects.
"""

import re
import os
import sys
from pathlib import Path

def minify_html(html_content):
    """
    Minify HTML by removing unnecessary whitespace, comments, and empty lines.
    """
    # Remove HTML comments (but preserve conditional comments)
    html_content = re.sub(r'<!--(?!\s*\[if\s).*?-->', '', html_content, flags=re.DOTALL)
    
    # Remove extra whitespace between tags
    html_content = re.sub(r'>\s+<', '><', html_content)
    
    # Remove whitespace at the beginning and end of lines
    html_content = re.sub(r'^\s+|\s+$', '', html_content, flags=re.MULTILINE)
    
    # Remove empty lines
    html_content = re.sub(r'\n\s*\n', '\n', html_content)
    
    # Compress CSS (remove unnecessary spaces in CSS)
    def compress_css_block(match):
        css_content = match.group(1)
        # Remove spaces around CSS operators
        css_content = re.sub(r'\s*([{}:;,>+~])\s*', r'\1', css_content)
        # Remove spaces after opening parentheses and before closing parentheses
        css_content = re.sub(r'\(\s+', '(', css_content)
        css_content = re.sub(r'\s+\)', ')', css_content)
        # Remove extra spaces
        css_content = re.sub(r'\s+', ' ', css_content)
        return f'<style>{css_content}</style>'
    
    html_content = re.sub(r'<style[^>]*>(.*?)</style>', compress_css_block, html_content, flags=re.DOTALL)
    
    # Compress JavaScript (basic compression)
    def compress_js_block(match):
        js_content = match.group(1)
        # Remove extra spaces around operators
        js_content = re.sub(r'\s*([{}();,=])\s*', r'\1', js_content)
        # Remove extra spaces
        js_content = re.sub(r'\s+', ' ', js_content)
        return f'<script>{js_content}</script>'
    
    html_content = re.sub(r'<script[^>]*>(.*?)</script>', compress_js_block, html_content, flags=re.DOTALL)
    
    # Final cleanup
    html_content = html_content.strip()
    
    return html_content

def escape_for_progmem(html_content):
    """
    Escape HTML content for use in C++ raw string literals.
    """
    # Escape backslashes first
    html_content = html_content.replace('\\', '\\\\')
    
    # Escape quotes
    html_content = html_content.replace('"', '\\"')
    
    return html_content

def generate_progmem_string(html_content, variable_name):
    """
    Generate a PROGMEM string declaration for Arduino.
    """
    minified = minify_html(html_content)
    
    # Calculate original and compressed sizes
    original_size = len(html_content)
    compressed_size = len(minified)
    compression_ratio = (1 - compressed_size / original_size) * 100
    
    print(f"{variable_name}:")
    print(f"  Original size: {original_size} bytes")
    print(f"  Compressed size: {compressed_size} bytes")
    print(f"  Compression: {compression_ratio:.1f}%")
    
    # Create the PROGMEM string
    progmem_string = f'const char {variable_name}[] PROGMEM = R"rawliteral(\n{minified}\n)rawliteral";\n\n'
    
    return progmem_string

def main():
    # Get the current directory (where the script is located)
    script_dir = Path(__file__).parent
    
    # Define file paths
    index_html_path = script_dir / "index.html"
    order_html_path = script_dir / "order.html"
    frontend_h_path = script_dir / "Frontend.h"
    
    # Check if input files exist
    if not index_html_path.exists():
        print(f"Error: {index_html_path} not found!")
        return 1
    
    if not order_html_path.exists():
        print(f"Error: {order_html_path} not found!")
        return 1
    
    try:
        # Read HTML files
        print("Reading HTML files...")
        with open(index_html_path, 'r', encoding='utf-8') as f:
            index_html = f.read()
        
        with open(order_html_path, 'r', encoding='utf-8') as f:
            order_html = f.read()
        
        print("Generating PROGMEM strings...")
        
        # Generate PROGMEM strings
        index_progmem = generate_progmem_string(index_html, "indexPage")
        order_progmem = generate_progmem_string(order_html, "orderPage")
        
        # Generate Frontend.h content
        frontend_content = f"""#ifndef FRONTEND_H
#define FRONTEND_H

#include <Arduino.h>

// Auto-generated HTML pages for Arduino web server
// Generated by html_to_progmem.py

{index_progmem}{order_progmem}#endif // FRONTEND_H
"""
        
        # Write to Frontend.h
        with open(frontend_h_path, 'w', encoding='utf-8') as f:
            f.write(frontend_content)
        
        print(f"\nFrontend.h has been generated successfully!")
        print(f"Location: {frontend_h_path}")
        print(f"Total size: {len(frontend_content)} bytes")
        
        return 0
        
    except Exception as e:
        print(f"Error: {e}")
        return 1

if __name__ == "__main__":
    sys.exit(main())